#!/usr/bin/env python3
"""Orchestrator for the entuned.co -> Substack cross-post (skill: substack-cross-post).

Runs strict preflight over the site-side artifacts, publishes to Substack
via publish_to_substack.py, then verifies the live post via verify_post.py.
Hard-halts (non-zero exit) on the first failed check — fix the underlying
problem, never stub around it.

Usage:
    python3 cross_post.py blog-<slug> --json /tmp/rewrite.json [--no-medium] [--no-send]

Medium is published by default after Substack verifies (mandatory leg,
Daniel 2026-07-17); pass --no-medium only with Daniel's explicit say-so.

The JSON payload:
    {
      "title":    "Source title verbatim",
      "subtitle": "Faithful one-sentence summary.",
      "body_html": "<p>...</p><h2>...</h2>...",   # OR "body": markdown-ish text
      "hero_alt": "descriptive alt text"          # optional; falls back to YAML alt
    }
If "body" (plain text: blank-line paragraphs, "## " headings, *em*) is
given instead of "body_html", it is converted here. The canonical inline
CTA paragraph is appended automatically if absent.

Site-side facts (since 2026-07-11): sitemap.xml and llms.txt are
AUTO-GENERATED by build.py — preflight verifies the built outputs contain
the post, it does not ask for manual entries.
"""
import argparse
import glob
import html as html_mod
import json
import os
import re
import subprocess
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
WEBSITE = os.path.abspath(os.path.join(HERE, ".."))
POSTS_DIR = os.path.join(HERE, "posts")
CTA_HTML = ('<p>I built a tool that does this. It’s called Entuned, it '
            'generates original music for your store’s specific customer, '
            'and the base tier is free. '
            '<a href="https://app.entuned.co/start">https://app.entuned.co/start</a></p>')
BANNED = [
    (r"—", "em dash"),
    (r"\bzones?\b", '"zones" (not a product concept)'),
    (r"\bday-?parting\b", '"day-parting" (use Outcome Scheduling)'),
    (r"\bEssentials\b", '"Essentials" (tier is Entuned Free)'),
]


def fail(msg):
    print(f"PREFLIGHT FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def check(cond, msg):
    if not cond:
        fail(msg)
    print(f"  ok: {msg}")


def http_status(url):
    req = urllib.request.Request(url, method="HEAD",
                                 headers={"User-Agent": "Mozilla/5.0"})
    try:
        return urllib.request.urlopen(req, timeout=30).status
    except urllib.error.HTTPError as e:
        return e.code
    except OSError:
        return 0


def body_to_html(body):
    """Convert the skill's plain-text body (blank-line paragraphs, '## '
    headings, *emphasis*) to the HTML the Tiptap paste expects."""
    out, para = [], []

    def flush():
        nonlocal para
        text = " ".join(para).strip()
        if text:
            t = html_mod.escape(text, quote=False)
            t = re.sub(r"\*([^*]+)\*", r"<em>\1</em>", t)
            out.append(f"<p>{t}</p>")
        para = []

    for ln in body.split("\n"):
        if ln.startswith("## "):
            flush()
            out.append(f"<h2>{html_mod.escape(ln[3:].strip(), quote=False)}</h2>")
        elif ln.startswith("# ") or not ln.strip():
            flush()
        else:
            para.append(ln.strip())
    flush()
    return "\n".join(out)


def preflight(page, slug, payload, skip_live=False, custom_cta=False):
    print("— preflight —")
    src = os.path.join(WEBSITE, "_src", "pages", page)
    check(os.path.isdir(src), f"source dir {src}")

    cfg_path = os.path.join(src, "config.json")
    check(os.path.exists(cfg_path), "config.json present")
    with open(cfg_path) as f:
        cfg = json.load(f)
    check(cfg.get("output") == f"blog/{slug}.html", f'config output = blog/{slug}.html')

    yaml_path = os.path.join(src, "content.yaml")
    check(os.path.exists(yaml_path), "content.yaml present (YAML posts only — no raw HTML)")
    check(not os.path.exists(os.path.join(src, "sections", "01-content.html")),
          "no legacy sections/01-content.html")
    with open(yaml_path) as f:
        y = f.read()
    for field in ("title:", "meta_description:", "hero:"):
        check(field in y, f"content.yaml has {field.rstrip(':')}")
    for block in ("key_takeaways", "subhead", "cta", "related"):
        check(f"type: {block}" in y, f"content.yaml has {block} section")

    img = os.path.join(WEBSITE, "img", "blog", f"{slug}.jpg")
    check(os.path.exists(img), f"hero image on disk: img/blog/{slug}.jpg")
    check(os.path.getsize(img) <= 500_000,
          f"hero image under 500KB ({os.path.getsize(img)} bytes)")

    built = os.path.join(WEBSITE, "blog", f"{slug}.html")
    check(os.path.exists(built), f"built page blog/{slug}.html (run build.py)")
    check(os.path.getmtime(built) >= os.path.getmtime(yaml_path),
          "built page newer than content.yaml (rebuild if this fails)")
    for artifact in ("sitemap.xml", "llms.txt", "blog.html"):
        with open(os.path.join(WEBSITE, artifact)) as f:
            check(slug in f.read(), f"{artifact} contains the post (auto-generated by build.py)")

    if skip_live:
        print("  (live checks skipped)")
    else:
        page_url = f"https://entuned.co/blog/{slug}.html"
        hero_url = f"https://entuned.co/img/blog/{slug}.jpg"
        check(http_status(page_url) == 200, f"live: {page_url}")
        check(http_status(hero_url) == 200, f"live: {hero_url} (pasted by URL into Substack)")

    print("— payload checks —")
    for k in ("title", "subtitle"):
        check(bool(payload.get(k)), f"payload has {k}")
    check(bool(payload.get("body_html")), "payload has body_html")
    for pat, name in BANNED:
        hits = re.findall(pat, payload["body_html"] + payload["subtitle"] + payload["title"])
        check(not hits, f"no banned term: {name}")
    if custom_cta:
        # --custom-cta (Daniel-approved per post): no listen invite — the
        # /start link must be ABSENT, and the body must still end cleanly.
        check("app.entuned.co/start" not in payload["body_html"],
              "custom CTA: no /start link anywhere (no listen invite)")
        check(payload["body_html"].rstrip().endswith("</p>"),
              "body ends with a closing paragraph")
    else:
        check(payload["body_html"].count('href="https://app.entuned.co/start"') == 1,
              "canonical CTA link present exactly once")
        check(payload["body_html"].rstrip().endswith("</p>")
              and "app.entuned.co/start" in payload["body_html"][-300:],
              "CTA is the final paragraph")

    m = re.search(r"^title:\s*[\"']?(.+?)[\"']?\s*$", y, re.M)
    if m:
        check(payload["title"] == m.group(1),
              f"payload title matches content.yaml title verbatim")
    m = re.search(r"^\s*alt:\s*[\"']?(.+?)[\"']?\s*$", y, re.M)
    payload.setdefault("hero_alt", m.group(1) if m else "")
    check(bool(payload["hero_alt"]), "hero alt text available")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("page", help="source page dir name, e.g. blog-my-slug")
    ap.add_argument("--json", required=True, help="rewrite payload JSON path")
    ap.add_argument("--medium", action="store_true",
                    help="(deprecated, now the default) also cross-post to Medium")
    ap.add_argument("--no-medium", action="store_true",
                    help="skip the Medium leg (requires Daniel's explicit say-so)")
    ap.add_argument("--no-send", action="store_true", help="Substack draft only, don't publish")
    ap.add_argument("--skip-live", action="store_true",
                    help="skip live-URL checks (pre-push dry run; publish will still need them)")
    ap.add_argument("--preflight-only", action="store_true",
                    help="run all checks and stop — no payload record, no browser")
    ap.add_argument("--custom-cta", action="store_true",
                    help="post ends with a Daniel-approved custom close instead of the "
                         "canonical Start Free CTA; /start link must be absent")
    args = ap.parse_args()

    page = args.page
    if not page.startswith("blog-"):
        fail(f"page should be the source dir name blog-<slug>, got {page}")
    slug = page[len("blog-"):]

    with open(args.json) as f:
        payload = json.load(f)
    if not payload.get("body_html") and payload.get("body"):
        payload["body_html"] = body_to_html(payload["body"])
    if (not args.custom_cta and payload.get("body_html")
            and "app.entuned.co/start" not in payload["body_html"]):
        payload["body_html"] = payload["body_html"].rstrip() + "\n" + CTA_HTML

    preflight(page, slug, payload, skip_live=args.skip_live, custom_cta=args.custom_cta)
    if args.preflight_only:
        print("PREFLIGHT OK (stopped before publish)")
        return

    # record the payload
    os.makedirs(POSTS_DIR, exist_ok=True)
    existing = [int(os.path.basename(p).split("_")[0])
                for p in glob.glob(os.path.join(POSTS_DIR, "[0-9]*_*.json"))]
    n = max(existing, default=0) + 1
    payload["slug"] = slug
    payload["hero_url"] = f"https://entuned.co/img/blog/{slug}.jpg"
    record = os.path.join(POSTS_DIR, f"{n:03d}_{slug}.json")
    with open(record, "w") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"payload recorded: {os.path.relpath(record, HERE)}")

    print("— publish (Substack) —")
    cmd = [sys.executable, os.path.join(HERE, "publish_to_substack.py"), "--payload", record]
    if args.no_send:
        cmd.append("--no-send")
    r = subprocess.run(cmd, cwd=HERE)
    if r.returncode != 0:
        sys.exit(r.returncode)
    if args.no_send:
        print("draft only — stopped before send, no postflight")
        return

    print("— postflight —")
    verify_cmd = [sys.executable, os.path.join(HERE, "verify_post.py"),
                  "--slug", slug, "--expected-title", payload["title"]]
    if args.custom_cta:
        verify_cmd.append("--no-cta-check")
    r = subprocess.run(verify_cmd, cwd=HERE)
    if r.returncode != 0:
        sys.exit(r.returncode)

    # Medium is a mandatory leg (Daniel, 2026-07-17). --no-medium is the
    # explicit opt-out; --medium is kept for backward compatibility.
    if not args.no_medium:
        print("— publish (Medium) —")
        r = subprocess.run([sys.executable, os.path.join(HERE, "publish_to_medium.py"),
                            "--payload", record,
                            "--canonical-url", f"https://entuned.co/blog/{slug}.html"], cwd=HERE)
        if r.returncode == 3:
            print("MEDIUM SIGNED OUT: sign in manually (Google account), then re-run\n"
                  f"  python3 publish_to_medium.py --payload {record} "
                  f"--canonical-url https://entuned.co/blog/{slug}.html",
                  file=sys.stderr)
            sys.exit(3)
        if r.returncode != 0:
            sys.exit(r.returncode)

    print("CROSS-POST COMPLETE")


if __name__ == "__main__":
    main()
